config/routes.rb
Rails.application.routes.draw do

  rutarel = (ENV['RUTA_RELATIVA'] || 'iap/miviap/')
  scope rutarel do
    devise_scope :usuario do
      get 'sign_out' => 'devise/sessions#destroy'
      get 'salir' => 'devise/sessions#destroy',
        as: :terminar_sesion

      post 'usuarios/iniciar_sesion', to: 'devise/sessions#create'
      get 'usuarios/iniciar_sesion', to: 'devise/sessions#new',
        as: :iniciar_sesion

      # El siguiente para superar mala generación del action en el formulario
      # cuando se autentica mal (genera
      # /puntomontaje/puntomontaje/usuarios/sign_in )
      if (Rails.configuration.relative_url_root != '/')
        ruta = File.join(Rails.configuration.relative_url_root,
                         'usuarios/sign_in')
        post ruta, to: 'devise/sessions#create'
      end
    end
    devise_for :usuarios, :skip => [:registrations], module: :devise
    as :usuario do
      get 'usuarios/edit' => 'devise/registrations#edit',
        :as => 'editar_registro_usuario'
      put 'usuarios/:id' => 'devise/registrations#update',
        :as => 'registro_usuario'
    end

    resources :accionesorg, path_names: {new: 'nueva', edit: 'edita' }

    resources :coyonturasregionales, path_names: {new: 'nuevo', edit: 'edita' }

    resources :observaciones, path_names: { new: 'nueva', edit: 'edita' }

    resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' }

    resources :zrcs, path_names: {new: 'nueva', edit: 'edita' }

    get 'proyectosfinancieros/:id/matriz_seguimiento' =>
      'cor1440_gen/proyectosfinancieros#matriz_seguimiento',
        as: 'matrizseguimiento'

    get 'regiones/de_depmun' => 'sivel2_gen/admin/regiones#de_depmun',
      as: 'region_de_depmun'

    namespace :admin do
      ab = ::Ability.new
      ab.tablasbasicas.each do |t|
        if (t[0] == "")
          c = t[1].pluralize
          resources c.to_sym,
            path_names: { new: 'nueva', edit: 'edita' }
        end
      end
    end

    root 'sivel2_gen/hogar#index'
  end

  mount Msip::Engine, at: rutarel, as: 'msip'
  mount Mr519Gen::Engine, at: rutarel, as: 'mr519_gen'
  mount Heb412Gen::Engine, at: rutarel, as: 'heb412_gen'
  mount Cor1440Gen::Engine, at: rutarel, as: 'cor1440_gen'
  mount Sivel2Gen::Engine, at: rutarel, as: 'sivel2_gen'
end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
  <%= Msip.titulo %>
<% end %>

<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo 'Casos' do %>
        <%= opcion_menu 'Listado', sivel2_gen.casos_path,
          desplegable: true %>
        <% if can?(:new, Sivel2Gen::Caso) %>
          <%= opcion_menu 'Validaciones', sivel2_gen.validarcasos_path,
            desplegable: true %>
          <%= opcion_menu 'Buscar repetidos', 
            sivel2_gen.buscarrepetidos_path, desplegable: true %>
          <%= opcion_menu 'Importar relatos XRLAT', 
            sivel2_gen.casos_importarrelatos_path, desplegable: true %>
        <% end %>
        <%= opcion_menu 'Geolocalización de casos sobre OpenStreetMap',
          sivel2_gen.casos_mapaosm_path, desplegable: true %>
        <%= opcion_menu 'Listado de víctimas y casos', 
          sivel2_gen.victimas_path, desplegable: true %>
        <%= opcion_menu 'Conteo demografía víctimas', 
          sivel2_gen.conteos_personas_path, desplegable: true %>
        <%= opcion_menu 'Conteo general de víctimas', 
          sivel2_gen.conteos_genvic_path, desplegable: true %>
        <%= opcion_menu 'Conteo de victimizaciones individuales', 
          sivel2_gen.conteos_victimizaciones_path,
          desplegable: true %>
        <%= opcion_menu "Árbol de presuntos responsables",
          sivel2_gen.arbol_presponsables_path, desplegable: true %>
        <%= opcion_menu 'Personas y/o víctimas', 
          msip.personas_path, desplegable: true %>
      <% end %>
      <%= despliega_abajo 'Acciones de IAP' do %>
        <%= opcion_menu 'Acciones', cor1440_gen.actividades_path,
          desplegable: true %>
        <%= opcion_menu 'Proyectos', 
          cor1440_gen.proyectosfinancieros_path, 
          desplegable: true %>
        <%= opcion_menu "Conteo por actividades de proyecto", 
          cor1440_gen.contar_actividades_path, desplegable: true %>
        <%= opcion_menu "Conteo por beneficiario y actividad de proyecto", 
          cor1440_gen.contar_actividades_beneficiarios_path, 
          desplegable: true %>
        <%= opcion_menu 'Medición de indicadores', 
          cor1440_gen.mindicadorespf_path, desplegable: true %>
      <% end %>
      <%= despliega_abajo 'Coyontura regional' do %>
        <%= opcion_menu 'Organizaciones acompañadas', 
          "#{msip.orgsociales_path}?filtro[bustipoorg_id]=1",
          desplegable: true %>
        <%= opcion_menu 'Acciones de organizaciones', 
          main_app.accionesorg_path, desplegable: true %>
        <%= opcion_menu 'Organizaciones (no acompañadas)',
          "#{msip.orgsociales_path}?filtro[bustipoorg_id]=2",
          desplegable: true %>
        <%= opcion_menu 'Coyunturas regionales', main_app.coyonturasregionales_path,
          desplegable: true %>
        <%= opcion_menu 'ZRC', main_app.zrcs_path,
          desplegable: true %>
      <% end %>
      <%= despliega_abajo 'Directorio' do %>
        <%= opcion_menu 'Instituciones civiles', 
          "#{msip.orgsociales_path}?filtro[bustipoorg_id]=3",
          desplegable: true %>
        <%= opcion_menu 'Fuerza Pública',
          "#{msip.orgsociales_path}?filtro[bustipoorg_id]=4",
          desplegable: true %>
        <%= opcion_menu 'Organismos internacionales',
          "#{msip.orgsociales_path}?filtro[bustipoorg_id]=5",
          desplegable: true %>
      <% end %>
    <% end %>

  <% end %>
  <%= grupo_menus :pull => :right do %>
    <%= despliega_abajo 'Documentos' do %>
      <%= opcion_menu 'Manual', 'https://docs.google.com/document/d/1VnKbtnujb-ukuNJBEmSswxKZYRkvH1W2OnkA8Ta755w/edit?usp=sharing',
        target: '_blank',
        desplegable: true %>
      <%= opcion_menu 'Nube', heb412_gen.sisini_path,
        desplegable: true %>
      <% if can? :manage, ::Heb412Gen::Plantillahcm %>
        <%= opcion_menu 'Plantillas para listados en hojas de calculo',
          heb412_gen.plantillashcm_path, desplegable: true %>
      <% end %>
      <% if can? :manage, ::Heb412Gen::Plantillahcr %>
        <%= opcion_menu 'Plantillas para un registro en hoja de calculo',
          heb412_gen.plantillashcr_path, desplegable: true %>
      <% end %>
      <% if current_usuario.nil? %>
        <%= opcion_menu 'Acerca de', sivel2_gen.acercade_path,
          desplegable: true %>
      <% end %>
    <% end %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo 'Administrar' do %>
        <%= opcion_menu 'Clave y tema', main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if session[:capturacaso_acordeon] %>
          <%= opcion_menu 'Ficha caso vertical ✓', 
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' %>
        <% else %>
          <%= opcion_menu 'Ficha caso vertical', 
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' %>
        <% end %>
        <% if can? :manage, Mr519Gen::Formulario %>
          <%= opcion_menu "Formularios", 
            mr519_gen.formularios_path,
            desplegable: true %>
        <% end %>
        <% if current_usuario.rol == Ability::ROLADMIN %>
          <%= opcion_menu 'Usuarios', main_app.usuarios_path,
            desplegable: true %>
          <%= opcion_menu 'Tablas Básicas', sivel2_gen.tablasbasicas_path,
            desplegable: true %>
          <%= opcion_menu 'Respaldo cifrado', msip.respaldo7z_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu 'Acerca de', sivel2_gen.acercade_path %>
      <%= opcion_menu 'Iniciar Sesión', main_app.iniciar_sesion_path %> 
    <% end %>
  <% end %>
<% end %>

<% content_for :piedepagina do %>
  <p> Datos de <a href='https://www.actionpeace.org/'>IAP</a><br>
  <span class='derechos'>
  Sistema de información de 
  <a href='https://github.com/pasosdeJesus/si_iap/'>código abierto</a>.
  <br/>
  Desarrollado por <a id='pasosdeJesus' href="http://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. 2023. 
  </span></p>
<% end %>

<%= render template: 'layouts/msip/application' %>